version: "1"

services:
  server:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db
    ports:
      - ${SPRING_SERVER_PORT}:8080
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_SERVER_PORT=${SPRING_SERVER_PORT}

  db:
    image: "postgres:13.1-alpine"
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=${SPRING_DATASOURCE_DB}
